on:
  [pull_request]

name: Check

jobs:
  check:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0

    - name: Build image
      run: |
        docker build .
